### ISSUE TITLE
Initial System Message Format

### ISSUE THREAD

**Issue by wtepfenhart** [wtepfenhart/Devdas#1]
We need a basic message format for system level messages detailing control commands, such as restart, stop, report, etc, which is used to get individual agents to fulfill system level needs. 
- [x] #4 Identify command set
- [x] #5 Identify User Cases
- [x] #6 Identify command arguments
- [x] #7 Propose initial system message format

**Comment by wtepfenhart** [comment]
The command message object now takes care of this so that the format can evolve simply by adding more functionality to the command message class.
